default:
  image: node:16.16.0

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - npm install
    - npx prisma generate
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    # - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prod --token=$VERCEL_TOKEN
